### ISSUE TITLE
AttributeError: type object 'MyClass' has no attribute '__event_slot_cls__'

### ISSUE THREAD

**Issue by Liriel** [pyeve/events#22]
Upgrading to the latest version on pypi `Events-0.4` gives an error message when running my program:

```
Traceback (most recent call last):
  File "./test.py", line 11, in <module>
    a = MyClass()
  File "./test.py", line 6, in __init__
    self.on_test()
  File "/tmp/eventsBug/env/lib64/python3.6/site-packages/events/events.py", line 99, in __getattr__
    self.__dict__[name] = ev = self.__event_slot_cls__(name)
  File "/tmp/eventsBug/env/lib64/python3.6/site-packages/events/events.py", line 89, in __getattr__
    (self.__class__.__name__, name))
AttributeError: type object 'MyClass' has no attribute '__event_slot_cls__'

```

the reason for this seems to be that I am raising the event in the constructor like this:

```
from events import Events
class MyClass(Events):
  __events__=("on_test")

  def __init__(self):
    self.on_test()

def handler():
  print("handler")

a = MyClass()
a.on_test += handler
a.on_test()
```
Is this a regression in the latest version or an intentional change?

I resolved the issue by downgrading back to version `0.3` like this

    pip3 install events==0.3

**Comment by OriDevTeam** [comment]
@Liriel That happens because the **Events** base class was not initialized in **MyClass**, try adding a super call as:
``` python
def __init__(self):
    super().__init__()
```

Tested and working in `Events-0.4`
